covid19/urls.py
# cursos/urls.py
from django.conf.urls import url,re_path
from django.urls import path,include,reverse
from covid19 import views

urlpatterns = [
    url(r'^$',views.HomePageView.as_view(),name="index"),
    url(r'noticias/', views.HomeNoticiasView.as_view(),name="noticias"),
    url(r'estadisticas/', views.HomeEstadisticasView.as_view(),name="estadisticas"),
    url(r'estadisticas_nacionales/', views.HomeEstadisticasNacionalesView.as_view(),name="estadisticas_nacionales"),
    url(r'^estadistica/list/$', views.HomeEstadisticasListView.as_view(),name="estadistica_list"),
    url(r'^estadistica/create/$', views.EstadisticaCreate.as_view(success_url='/estadisticas/list/'), name='estadistica_create'),
    url(r'^estadistica/(?P<pk>\d+)/update/$', views.EstadisticaUpdate.as_view(success_url='/estadistica/list/'), name='estadistica_update'),
    url(r'^estadistica/(?P<pk>\d+)/delete/$', views.EstadisticaDelete.as_view(success_url='/estadistica/list/'), name='estadistica_delete'),
    url(r'contacto/', views.ContactoCreate.as_view(),name="contacto"),
    re_path(r'^evaluacion/(?P<pk>\d+)/$', views.ContactoEvaluationView.as_view(),name="contacto_evaluacion"),
    url(r'biblioteca/', views.HomeBibliotecaView.as_view(),name="biblioteca"),
    url(r'algoritmos/', views.HomeAlgoritmosView.as_view(),name="algoritmos"),
    url(r'videos/', views.HomeVideosView.as_view(),name="videos"),
    url(r'^documento/create/$', views.DocumentoCreate.as_view(success_url='/biblioteca/'), name='documento_create0'),
    url(r'^documento/(?P<pk>\d+)/update/$', views.DocumentoUpdate.as_view(success_url='/biblioteca/'), name='documento_update0'),
    url(r'^documento/(?P<pk>\d+)/delete/$', views.DocumentoDelete.as_view(success_url='/biblioteca/'), name='documento_delete0'),
#    url(r'^documento/create/(?P<tipo>0)/$', views.DownloadDocumentCreate.as_view(success_url='/biblioteca/'), name='documento_create0'),
#    url(r'^documento/create/(?P<tipo>1)/$', views.DownloadDocumentCreate.as_view(success_url='/biblioteca/'), name='documento_create1'),
#    url(r'^documento/create/(?P<tipo>2)/$', views.VideoCreate.as_view(success_url='/biblioteca/'), name='documento_create2'),
#    url(r'^documento/(?P<pk>\d+)/update/(?P<tipo>0)/$', views.DownloadDocumentUpdate.as_view(success_url='/biblioteca/'), name='documento_update0'),
#    url(r'^documento/(?P<pk>\d+)/update/(?P<tipo>1)/$', views.DownloadDocumentUpdate.as_view(success_url='/biblioteca/'), name='documento_update1'),
#    url(r'^documento/(?P<pk>\d+)/update/(?P<tipo>2)/$', views.VideoUpdate.as_view(success_url='/biblioteca/'), name='documento_update2'),
#    url(r'^documento/(?P<pk>\d+)/delete/(?P<tipo>0)/$', views.DocumentoDelete.as_view(success_url='/biblioteca/'), name='documento_delete0'),
#    url(r'^documento/(?P<pk>\d+)/delete/(?P<tipo>1)/$', views.DocumentoDelete.as_view(success_url='/biblioteca/'), name='documento_delete1'),
#    url(r'^documento/(?P<pk>\d+)/delete/(?P<tipo>2)/$', views.DocumentoDelete.as_view(success_url='/biblioteca/'), name='documento_delete2'),
    re_path(r'^documento/(?P<pk>\d+)/$', views.DetalleDocumentoView.as_view(),name="detalleDocumento"),
    re_path(r'^noticia/(?P<pk>\d+)/$', views.DetalleNoticiaView.as_view(),name="detalle"),
    url(r'^noticia/create/$', views.NoticiaCreate.as_view(success_url='/noticias/'), name='noticia_create'),
    url(r'^noticia/(?P<pk>\d+)/update/$', views.NoticiaUpdate.as_view(success_url='/noticias/'), name='noticia_update'),
    url(r'^noticia/(?P<pk>\d+)/delete/$', views.NoticiaDelete.as_view(success_url='/noticias/'), name='noticia_delete'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('casos_hospital_chart/', views.casos_hospital_chart, name='casos_hospital_chart'),
    url(r'about/', views.AboutView.as_view(),name="about"),
]

elpino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('covid19.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid19/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
import os

# Create your models here.
class Noticia(models.Model):
    fecha=models.DateTimeField()
    titulo=models.CharField(max_length=128)
    autor=models.CharField(max_length=128)
    imagen=models.FileField(upload_to='news/%Y/%m/%d/')
    descripcion=models.CharField(max_length=1024)
    noticias=models.Manager()

    def __str__(self):
        return "{}".format(self.titulo)

    def delete(self, *args, **kwargs):
        if(self.imagen):
            os.remove(os.path.join(settings.MEDIA_ROOT, self.imagen.name))
        super(Noticia,self).delete(*args,**kwargs)

class Documento(models.Model):
    ARCHIVO = 0
    ALGORITMO = 1
    VIDEO = 2
    TIPO_CHOICES = [
        (ARCHIVO, 'Archivo'),
        (ALGORITMO, 'Flujograma'),
        (VIDEO, 'Video'),
    ]
    tipo = models.IntegerField(
        choices=TIPO_CHOICES,
        default=ARCHIVO,
    )
    titulo=models.CharField(max_length=128)
    link=models.CharField(max_length=256,blank=True,null=True)
    archivo=models.FileField(blank=True,null=True,upload_to='documents/%Y/%m/%d/')
    fecha=models.DateTimeField(auto_now_add=True)
    documentos=models.Manager()

    def delete(self, *args, **kwargs):
        if(self.archivo):
            os.remove(os.path.join(settings.MEDIA_ROOT, self.archivo.name))
        super(Documento,self).delete(*args,**kwargs)

class Estadistica(models.Model):
    fecha=models.DateField()
    confirmados_Hospital=models.IntegerField()
    examenes_Hospital=models.IntegerField()
    hospital_VMI=models.IntegerField()
    hospital_TOTAL=models.IntegerField()
    funcionarios_contagiados=models.IntegerField()
    funcionarios_PCR=models.IntegerField()
    estadisticas=models.Manager()

SERVICIOS = (
        (1, 'Servicio 1'),
        (2, 'Servicio 2'),
)

ACTIVIDADES = (
        (1, 'Médico'),
        (2, 'Profesional de la Salud'),
        (3, 'Técnico de la Salud'),
        (4, 'Administrativo'),
)

TIPO_CONTRATO = (
        (1, 'Contrata'),
        (2, 'Honorario'),
        (3, 'Otro')
)

class Usuario(AbstractUser):
    nombre = models.CharField(max_length=30)
    apellido_paterno = models.CharField(max_length=30)
    apellido_materno = models.CharField(max_length=30)
    fecha_nacimiento = models.DateField()
    servicio = models.CharField(max_length=30)
    actividad = models.IntegerField(choices=ACTIVIDADES,default=1)
    contrato=models.IntegerField(choices=TIPO_CONTRATO,default=3)
    email = models.EmailField(max_length=254, help_text='')
    telefono = models.CharField(max_length=30)

class Contacto(models.Model):
    usuario=models.ForeignKey(Usuario,on_delete=models.CASCADE)
    fecha_registro=models.DateTimeField(auto_now_add=True)
    contacto_confirmado=models.BooleanField()
    sintomas=models.BooleanField()
    contacto_10minutos=models.BooleanField()
    contacto_2horas=models.BooleanField()
    contactos=models.Manager()
    status=models.IntegerField()

covid19/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Noticia, Estadistica, Documento, Contacto
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django import forms
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe
from django.http import JsonResponse
from django.conf import settings
from django.shortcuts import redirect
from covid19.models import Usuario

class CustomLoginRequiredMixin(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if "username" not in request.session:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        return super().dispatch(request, *args, **kwargs)

class HomePageView(CustomLoginRequiredMixin,TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'noticias.html', {'noticias': Noticia.noticias.all()})

class AboutView(CustomLoginRequiredMixin,TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'about.html')

class HomeNoticiasView(CustomLoginRequiredMixin,TemplateView):
    #permission_required='puede_buscar_cursos'
    def get(self, request, **kwargs):
        return render(request, 'noticias.html', {'noticias': Noticia.noticias.all().order_by("-fecha")})

class HomeEstadisticasNacionalesView(CustomLoginRequiredMixin,TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'estadisticas_nacionales.html')

class HomeEstadisticasView(CustomLoginRequiredMixin,TemplateView):
    #permission_required='puede_buscar_cursos'
    def get(self, request, **kwargs):
        try:
            return render(request, 'estadisticas.html', {'estadisticas': Estadistica.estadisticas.latest('fecha')})
        except:
            return render(request, 'estadisticas.html', {'estadisticas':
            {'confirmados_Hospital':0,
            'examenes_Hospital':0,
            'hospital_contagios':0,
            'hospital_recuperados':0
            }})

class HomeEstadisticasListView(CustomLoginRequiredMixin,TemplateView):
    #permission_required='puede_buscar_cursos'
    def get(self, request, **kwargs):
        try:
            return render(request, 'estadisticas_list.html', {'estadisticas': Estadistica.estadisticas.order_by('fecha')})
        except:
            return render(request, 'estadisticas_list.html', {'estadisticas': []})   

class HomeAlgoritmosView(CustomLoginRequiredMixin,TemplateView):
    #permission_required='puede_buscar_cursos'
    def get(self, request, **kwargs):
        return render(request, 'biblioteca.html',
        {'documentos': Documento.documentos.filter(tipo=1).order_by('-fecha'),'titulo': 'Flujogramas', 'tipo':1})

class HomeBibliotecaView(CustomLoginRequiredMixin,TemplateView):
    #permission_required='puede_buscar_cursos'
    def get(self, request, **kwargs):
        return render(request, 'biblioteca.html',
        {'documentos': Documento.documentos.all().order_by('-fecha'), 'titulo': 'Biblioteca','tipo':0})

class HomeVideosView(CustomLoginRequiredMixin,TemplateView):
    #permission_required='puede_buscar_cursos'
    def get(self, request, **kwargs):
        return render(request, 'biblioteca.html',
        {'documentos': Documento.documentos.filter(tipo=2).order_by('-fecha'), 'titulo': 'Videos','tipo':2})

class DetalleNoticiaView(CustomLoginRequiredMixin,TemplateView):
    def get(self, request, **kwargs):
        id=kwargs["pk"]
        return render(request, 'noticia.html', {'noticia': Noticia.noticias.get(id=id)})

class NoticiaCreate(CustomLoginRequiredMixin,CreateView):
    model = Noticia
    template_name='./noticia_form.html'
    fields = ['fecha','titulo','imagen','descripcion']
    
    def form_valid(self,form):
        autor=Usuario.objects.get(username=self.request.user)
        form.instance.autor=autor.nombre+" "+autor.apellido_paterno
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super(NoticiaCreate, self).get_form(form_class)
        form.fields['fecha'].input_formats=['%m/%d/%Y %H:%M %p']
        form.fields['fecha'].widget = forms.DateTimeInput(attrs={
            'class': 'datetimepicker-input',
            'data-target': '#datetimepicker1'})
        form.fields['titulo'].widget = forms.Textarea(attrs={'cols': 80, 'rows': 2})
        form.fields['descripcion'].widget = forms.Textarea(attrs={'cols': 80, 'rows': 15})
        return form

class NoticiaUpdate(CustomLoginRequiredMixin,UpdateView):
    model = Noticia
    template_name='./noticia_form.html'
    fields = ['fecha','titulo','imagen','descripcion']

    def get_form(self, form_class=None):
        form = super(NoticiaUpdate, self).get_form(form_class)
        form.fields['fecha'].input_formats=['%m/%d/%Y %H:%M %p']
        form.fields['fecha'].widget = forms.DateTimeInput(attrs={
            'class': 'datetimepicker-input',
            'data-target': '#datetimepicker1'})
        form.fields['titulo'].widget = forms.Textarea(attrs={'cols': 80, 'rows': 2})
        form.fields['descripcion'].widget = forms.Textarea(attrs={'cols': 80, 'rows': 15})
        return form

class NoticiaDelete(CustomLoginRequiredMixin,DeleteView):
    model = Noticia
    template_name='./noticia_confirm_delete.html'
    success_url = reverse_lazy('noticias')

class DetalleDocumentoView(CustomLoginRequiredMixin,TemplateView):
    def get(self, request, **kwargs):
        id=kwargs["pk"]
        return render(request, 'documento.html', {'documento': Documento.documentos.get(id=id)})

class DocumentValidationMixin:
    def form_valid(self,form):
        if form.cleaned_data["tipo"] == 2:
            link=form.cleaned_data["link"]
            if not link:
                form.add_error("link","Para videos debe indicar el link a youtube")
                return self.form_invalid(form)
            else:
                p=link.rfind("/")
                link=link[p+1:]
                if(p==-1) or link=="":
                    form.add_error("link","El link ingresado no es válido")
                    return self.form_invalid(form)
            if "archivo" in form.cleaned_data and form.cleaned_data["archivo"]:
                form.add_error("link","No puede subir archivos de video, por favor indique el link a youtube")
                return self.form_invalid(form)
        else:
            if not form.cleaned_data["archivo"]:
                form.add_error("archivo","Debe indicar un archivo")
                return self.form_invalid(form)
        
        return super().form_valid(form)

class DocumentoCreate(CustomLoginRequiredMixin,DocumentValidationMixin,CreateView):
    model = Documento
    template_name='./documento_form.html'
    fields = ['tipo','titulo','link','archivo']

    def get_form(self, form_class=None):
        form = super(DocumentoCreate, self).get_form(form_class)

        return form

class DownloadDocumentCreate(DocumentoCreate):
    fields = ['tipo','titulo','archivo']

class VideoCreate(DocumentoCreate):
    fields = ['tipo','titulo','link']

class DocumentoUpdate(DocumentValidationMixin,UpdateView):
    model = Documento
    template_name='./documento_form.html'
    fields = ['tipo','titulo','link','archivo']

    def get_form(self, form_class=None):
        form = super(DocumentoUpdate, self).get_form(form_class)
        form.fields['tipo'].widget.attrs={'disabled':'disabled'}

        return form

class DownloadDocumentUpdate(CustomLoginRequiredMixin,DocumentoUpdate):
    fields = ['tipo','titulo','archivo']

class VideoUpdate(CustomLoginRequiredMixin,DocumentoUpdate):
    fields = ['tipo','titulo','link']

class DocumentoDelete(CustomLoginRequiredMixin,DeleteView):
    model = Documento
    template_name='./documento_confirm_delete.html'
    success_url = reverse_lazy('biblioteca')

class CustomRadioSelect(forms.RadioSelect):
    template_name="./customradio.html"

class ContactoCreate(CustomLoginRequiredMixin,CreateView):
    model=Contacto
    template_name='./contacto_form.html'
    fields=['contacto_confirmado','sintomas','contacto_10minutos','contacto_2horas']

    def form_valid(self,form):
        form.instance.usuario=self.request.user
        if not form.instance.sintomas and not form.instance.contacto_confirmado and not form.instance.contacto_10minutos and not form.instance.contacto_2horas:
            form.instance.status=0
        else:
            form.instance.status=1
        return super().form_valid(form)

    def get_form(self, form_class=None):
        CHOICES = [(True,"Sí"),(False,"No")]
        form = super(ContactoCreate, self).get_form(form_class)
        form.fields['contacto_confirmado'].widget = forms.RadioSelect(choices=CHOICES)
        form.fields['contacto_confirmado'].label = "¿Ha tenido contacto con un caso confirmado o sospechoso?"
        form.fields['sintomas'].widget = forms.RadioSelect(choices=CHOICES)
        form.fields['sintomas'].label = "¿Tiene Sintomas Respiratorios?"
        form.fields['contacto_10minutos'].widget = forms.RadioSelect(choices=CHOICES)
        form.fields['contacto_10minutos'].label = "¿Estuvo 15 minutos cara a cara a menos de 1 metro de una persona contagiada?"
        form.fields['contacto_2horas'].widget = forms.RadioSelect(choices=CHOICES)
        form.fields['contacto_2horas'].label = "¿Estuvo más de 2 horas con una persona contagiada en una habitación?"
        return form

    def get_success_url(self):
        return reverse_lazy('contacto_evaluacion', kwargs={'pk': self.object.pk})

class ContactoEvaluationView(CustomLoginRequiredMixin,TemplateView):
    def get(self, request, **kwargs):
        pk=kwargs["pk"]

covid19/templates/about.html
{% extends  'base.html' %}
{% load static %}

{% block content %}
<img src="{% static "images/HEP APP BANNER PATROCINIO.png" %}" class="mx-auto d-block img-fluid">
<p>
    Esta aplicación es un desarrollo elaborado por la contingencia nacional en el marco de la alianza colaborativa
    entre la Facultad de Ingeniería de la Universidad Andrés Bello y la Fundación El Pino, con el patrocinio de Fundación Clínica San Pedro.
    El objetivo principal de esta iniciativa es poder llegar a todos los funcionarios del Hospital El Pino
    con información oficial respecto a la situación que vive el mundo y poder disponibilizar para su lectura
    y visualización oportuna, los protocolos y flujogramas que se están desarrollando a diario.
</p>
<p align="center">
    Agradecemos nos hagan llegar sus sugerencias a <a href="mailto:fundacionelpino@gmail.com">fundacionelpino@gmail.com</a>.    
</p>
<p align="center">
    Desarrollado por: Ingeniería Civil Informática UNAB, 2020    
</p>
<img src="{% static "images/footer.png" %}" class="mx-auto d-block img-fluid">
{% endblock %}

covid19/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Hospital y CRS El Pino{% endblock %}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
         integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
         integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
         <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
         <link href="{% static "css/elpino.css" %}" rel="stylesheet">

         {% block head %}
        {% endblock %}
    </head>

    <body>
        {% include "navbar.html" %}

        <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

        <!-- Moment.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
        integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

        <!-- Tempus Dominus Bootstrap 4 -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
        integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        <script type="text/javascript" src="{% static "js/chartjs-plugin-colorschemes.min.js" %}"></script>

        <div class="container" style="margin: auto">
            {% block content %}
            {% endblock %}
        </div>

        {% include "footer.html" %}

        {% block scripts %}
        {% endblock %}
    </body>
</html>

covid19/templates/biblioteca.html
{% extends  'base.html' %}
{% load covid19_extras %}
{% load static %}
{% block content %}
<img src="{% static "images/HEP APP BANNER BIBLIOTECA.png" %}" class="mx-auto d-block img-fluid">
<div class="container mt-3">
  {% for documento in documentos %}
    <div class="media border p-3">
      {% if documento.tipo == 0 %}
        <a href="{{documento.archivo.url}}">
          <img src="{% static "iconic/svg/file.svg" %}" class="mr-3 mt-3" style="width:40px;">
          {{documento.titulo}}
        </a>
      {% endif %}
      {% if documento.tipo == 1 %}
        <a href="{{documento.archivo.url}}">
          <img src="{% static "iconic/svg/fork.svg" %}" class="mr-3 mt-3" style="width:40px;">
          {{documento.titulo}}
        </a>
      {% endif %}
      {% if documento.tipo == 2 %}
        <a href="/documento/{{ documento.id }}/">
          <img src="{% static "iconic/svg/video.svg" %}" class="mr-3 mt-3" style="width:40px;">
          {{documento.titulo}}
        </a>
      {% endif %}
      <div class="media-body">
        &nbsp;
      </div>
      {% if user.is_staff %}
        <div class="media-left">
          <a href="/documento/{{ documento.id }}/update/">
            <p><i class="fas fa-edit icon-3x"></i></p>
          </a>
          <a href="/documento/{{ documento.id }}/delete/">
            <p><i class="fas fa-minus-circle icon-3x"></i></p>
          </a>
        </div>
      {% endif %}
    </div>
  {% endfor %}
</div>
{% if user.is_staff %}
  <a class="btn btn-primary btn-lg" href="/documento/create/" role="button">Agregar</a>
{% endif %}
{% endblock %}

covid19/templates/documento_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<img src="{% static "images/HEP APP BANNER BIBLIOTECA.png" %}" class="mx-auto d-block img-fluid">

<form id="documento_form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
        <table class="table table-borderless">
        {% for field in form %}
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>
                    {{field}}
                    {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="2">
                <button type="submit" class="btn btn-lg btn-primary">Guardar</button>
            </td>
        </tr>
        </table>
</form>
<script type="text/javascript">
    function ajustar(x)
    {
        if(x.matches)
            $('#id_tipo').css("font-size","calc(100% + 1vw + 1vh)");
        else
            $('#id_tipo').css("font-size","medium");
    }
    $(function () {
        window.matchMedia('(max-width: 1024px)').addListener(ajustar);
    });
    $('#documento_form').submit(function(){
        $("#documento_form :disabled").removeAttr('disabled');
    });
</script>

{% endblock %}

covid19/templates/signup.html
{% extends  'base.html' %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h4 class="card-title">Regí­strese Aquí­</h4>

    <form method="post">
      {% csrf_token %}
      <table class="table table-borderless">
        {% for field in form %}
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>
                {% if field.name == "fecha_nacimiento" %}
                  {{field}}
                  <script type="text/javascript">
                      $(function () {
                          $('#id_fecha_nacimiento').datepicker({
                              dateFormat: 'dd/mm/yy',
                              changeMonth: true,
                              changeYear: true,
                              yearRange: "-70:+0",
                          });
                          $('#id_fecha_nacimiento').datepicker(
                              'setDate', $('#id_fecha').val()
                          );
                      });
                  </script>
                {% else %}
                  {{field}}
                {% endif %}
                  {% if field.help_text %}
                      <small style="color: grey">{{ field.help_text }}</small>
                  {% endif %}
                  {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                  {% endfor %}
                </td>
            </tr>
        {% endfor %}
      </table>
      <button type="submit" class="btn btn-primary btn-block">Registrar</button>
    </form>
  </div>
</div>
{% endblock %}